name: CI

# **What it does**: Runs tests.
# **Why we have it**: Ensures tests pass before merging code.

on:
    push:
        branches:
            - main
        paths-ignore:
            - "docs/**"
            - "*.md"
    pull_request:
        branches:
            - main
        paths-ignore:
            - "docs/**"
            - "*.md"
        types: [opened, ready_for_review, reopened, synchronize]

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
    group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
    cancel-in-progress: true

permissions:
    contents: read

jobs:
    dependency-review:
        name: Dependency Review
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Check out repo
              uses: actions/checkout@v5
              with:
                  persist-credentials: false

            - name: Dependency review
              uses: actions/dependency-review-action@56339e523c0409420f6c2c9a2f4292bbb3c07dd3 # v4.8.0

    lint:
        name: Lint Code
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Check out repo
              uses: actions/checkout@v5
              with:
                  persist-credentials: false

            - name: Setup Node
              uses: actions/setup-node@v6
              with:
                  check-latest: true
                  node-version-file: .nvmrc

            - name: Install
              run: npm i --ignore-scripts

            - name: Audit NPM package signatures and provenance attestations
              run: npm audit signatures

            - name: Run ESLint
              run: npm run lint:eslint

            - name: Run Prettier
              run: npm run lint:prettier

            - name: Run Licensee
              run: npm run lint:licenses

            - name: Run build
              run: npm run build --if-present

            - name: Run typecheck
              run: npm run typecheck --if-present

    commit-lint:
        name: Lint Commit Messages
        if: >
            github.event_name == 'push' ||
            (github.event_name == 'pull_request' && github.event.pull_request.user.login != 'dependabot[bot]')
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Check out repo
              uses: actions/checkout@v5
              with:
                  fetch-depth: 0
                  persist-credentials: false

            - name: Run Commitlint
              uses: wagoid/commitlint-github-action@b948419dd99f3fd78a6548d48f94e3df7f6bf3ed # v6.2.1
              with:
                  configFile: ./package.json

    automerge:
        name: Automerge Dependabot PRs
        needs: [dependency-review, lint]
        if: >
            github.event_name == 'pull_request' &&
            github.event.pull_request.head.repo.full_name == github.repository &&
            github.event.pull_request.user.login == 'dependabot[bot]'
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
            contents: write
        steps:
            - uses: fastify/github-action-merge-dependabot@e820d631adb1d8ab16c3b93e5afe713450884a4a # v3.11.1
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  merge-method: squash
